### PR TITLE
Add Go client to README

### PR DESCRIPTION
**Pull request by ertan**

### CODE REVIEW

**Comment by emlazzarin** [comment]
This is great, thanks for putting it together. Do you think it makes sense to wait until you have some tests and a bit more in place before adding it to the awesome list? [Traditionally, repos need to be >30 days old](https://github.com/sindresorhus/awesome-lint/blob/e8840c7af45b02152f2382979638aa1b63e5ac27/rules/git-repo-age.js#L7) before getting added to an awesome list, but if you think the repo is mature enough for inclusion we could put it in earlier.

**Comment by ertan** [comment]
hey Eddy, thanks for the review. I've been working on this project on and off since mid December, but it's not battle tested yet. I'm hoping to get it out there sooner so I have a better idea which parts need improvement. That said, I don't mind waiting 30 days but I'm not entirely sure how much I'll be able to contribute as my schedule is getting busier this month. We can play it by ear and merge it later.

**Comment by ertan** [comment]
hi! didn't have a chance to add much since but a couple of tests. do you think we can merge this PR so the library is more discoverable? thank you :)

**Comment by emlazzarin** [comment]
Looking good! Happy to merge.

**Pull request merged**
